### ISSUE TITLE
Work directly on Master?

### ISSUE THREAD

**Issue by mayamcdougall** [smcdougall/NotePaper#9]
For the last two releases, I've done all my work on a separate branch (testing) and merged it into master when it was done.  When I started that, I didn't know much about how GitHub works and I didn't know that when you tag a release you can get back to that point in time easily by using that tag.

Going forward, I'm considering doing most of the work on Master. I'm the only one working on NotePaper, so I don't really see why I should continue using a special bench for development.

@PhrozenByte What's your advice? Should working directly on Master be okay? Anything I should worry about? As always, thanks in advance for your help. :smile:

**Comment by PhrozenByte** [comment]
Depends on whether you want to (or need to) release bugfixes (i.e. `PATCH` versions) while developing the next `MAJOR`/`MINOR` version of NotePaper (e.g. Pico definitely requires a separate [`pico-1.1` branch](https://github.com/picocms/Pico/tree/pico-1.1), otherwise it would be impossible to release Pico 1.0.2). If you don't need bugfix releases and thus don't want to follow [Semantic Versioning](http://semver.org/), separate development branches aren't necessary and it's completely fine to work on `master`. You can find our thoughts about branching in our [`CONTRIBUTING.md`](https://github.com/picocms/Pico/blob/master/CONTRIBUTING.md#branching), this may give you a starting point.

**Comment by mayamcdougall** [comment]
Well, it has been my intention to use Semantic Versioning... (that's why I keep adding ".0" to everything) I just haven't had to fix anything yet besides a few readme typos.

I think my overall intention going forward is to push out smaller updates, faster.  `1.5` took _way_ too long and I added a lot more to it than I meant to.  It's taken me the last week just to update the readme and prepare other associated files for release.  It started out as `1.4.1`, but it became apparent pretty quickly that it would outgrow that number at the rate I was going.

I guess I'll probably stick to using a `testing` branch for now, but I'll try to keep it a short-lived testing branch.  I've been working on this version since early December and... well, oddly enough _I've_ been waiting a long time for my new features to come out.

I'll probably get a chance to deploy it to my server later tonight.  Updating the Pico config for four or five sites takes a while.  One of those sites is the [NotePaper demo site](http://development.sjmcdougall.com/pico-themes/NotePaper/), so if you check it out tomorrow you'll see the new version up. :smile:

Thanks again for the input.
